
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { OrvellaLogo } from "@/components/logo";
import Link from "next/link";
import { Button } from "@/components/ui/button";

function Header() {
  return (
    <header className="fixed top-0 left-0 right-0 z-50">
      <nav className="container mx-auto px-6 py-4 flex justify-between items-center">
        <Link href="/">
            <OrvellaLogo />
        </Link>
        <a href="https://discord.gg/rxJNyg9BUp" target="_blank" rel="noopener noreferrer">
          <Button className="bg-accent text-white hover:bg-accent/90 hover:shadow-[0_0_20px_theme(colors.accent)] transition-all duration-300 transform hover:-translate-y-1">Contact Staff</Button>
        </a>
      </nav>
    </header>
  );
}


export default function PoliciesPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-1 pt-24 pb-12">
        <div className="container mx-auto px-6">
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent">
              Orvella AI Policies
            </h1>
            <p className="text-lg md:text-xl text-foreground/80 max-w-2xl mx-auto mt-4">
              Last Updated: {new Date().toLocaleDateString()}
            </p>
          </div>

          <div className="space-y-8 max-w-4xl mx-auto">
            <Card className="glassmorphic">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">1. Privacy Policy</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground/80">
                <p>
                  At Orvella AI, we are committed to protecting your privacy. This policy outlines how we collect, use, and safeguard your information.
                </p>
                <p>
                  <strong>Data Collection:</strong> We collect the text you input into our AI tools to process your requests. If you create an account, we may also collect basic account information. We use this data solely to provide and improve our services.
                </p>
                <p>
                  <strong>Data Usage:</strong> Your data is used to generate responses, refine our AI models, and enhance the user experience. We will never sell your personal data to third parties.
                </p>
                <p>
                  <strong>Data Security:</strong> We implement industry-standard security measures to protect your information from unauthorized access, alteration, or disclosure.
                </p>
              </CardContent>
            </Card>

            <Card className="glassmorphic">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">2. User Guidelines</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground/80">
                <p>
                  We expect all users to interact with Orvella AI respectfully and responsibly.
                </p>
                <p>
                  <strong>Acceptable Use:</strong> You agree not to use our services to generate content that is illegal, hateful, harassing, violent, or otherwise malicious. This includes misinformation and spam.
                </p>
                <p>
                  <strong>Consequences:</strong> Violation of these guidelines may result in a temporary or permanent ban from our services, at our sole discretion.
                </p>
              </CardContent>
            </Card>

            <Card className="glassmorphic">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">3. Content Policy</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground/80">
                <p>
                  While our AI strives for accuracy and quality, the generated content comes with certain caveats.
                </p>
                <p>
                  <strong>AI-Generated Content:</strong> The outputs from our AI are generated by a machine and may be unexpected, imperfect, or inaccurate. Always review and verify the information before use.
                </p>
                <p>
                  <strong>No Professional Advice:</strong> Content generated by Orvella AI should not be considered professional, medical, legal, or financial advice. You are responsible for how you interpret and apply the information.
                </p>
              </CardContent>
            </Card>

            <Card className="glassmorphic">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">4. Support</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground/80">
                <p>
                  Need help? Have feedback? We'd love to hear from you.
                </p>
                <p>
                  For assistance, bug reports, or suggestions, please join our official Discord server. Our team and community are there to help.
                </p>
                <a href="https://discord.gg/rxJNyg9BUp" target="_blank" rel="noopener noreferrer">
                  <Button variant="secondary">Join our Discord</Button>
                </a>
              </CardContent>
            </Card>

            <Card className="glassmorphic">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">5. Limitation of Liability</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground/80">
                <p>
                  Orvella AI is provided "as is" without warranties of any kind. We are not liable for any damages, losses, or other consequences resulting from your use of our service. You are fully responsible for your use of the generated content and for complying with all applicable laws.
                </p>
              </CardContent>
            </Card>

            <Card className="glassmorphic">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">6. Changes to Policies</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground/80">
                <p>
                  We may update these policies from time to time to reflect changes in our services or for other operational, legal, or regulatory reasons. We encourage you to review this page periodically for any updates.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
